version: "3"

services: 

    accesscorp-users-api:
        image: MatheusCFBT/accesscorp-users-api:latest
        container_name: accesscorp-users-api
        build: 
            context: ..
            dockerfile: AccessCorp.Users/AccessCorp.WebApi/Dockerfile
        ports:
            - "5001:5001"
            - "5003:5003"
        environment: 
            - ASPNETCORE_ENVIRONMENT=Production 
            - ASPNETCORE_URLS=http://*:7100
        depends_on:
            -  accesscorp-identity-api

    accesscorp-identity-api:
        image: MatheusCFBT/accesscorp-identity-api:latest
        container_name: accesscorp-identity-api
        build:
            context: ..
            dockerfile: AccessCorp.Identity/AccessCorp.WebApi/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Production 
            - ASPNETCORE_URLS=http://*:7061