services: 

    sql-server:
        image: MatheusCFBT/accesscorp-sql-server:latest
        container_name: accesscorp-sql-server
        build:
            context: ../sql
            dockerfile: ./Dockerfile
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: "Accesscorp@123"
            ACCEPT_EULA: "Y"

    accesscorp-users-api:
        image: MatheusCFBT/accesscorp-users-api:latest
        container_name: accesscorp-users-api
        build: 
            context: ..
            dockerfile: AccessCorp.Users/AccessCorp.WebApi/Dockerfile
        ports:
            - "5164:5164"
        environment: 
            - ASPNETCORE_ENVIRONMENT=Docker 
            - ASPNETCORE_URLS=http://*:5164
        depends_on:
            -  accesscorp-identity-api

    accesscorp-identity-api:
        image: MatheusCFBT/accesscorp-identity-api:latest
        container_name: accesscorp-identity-api
        build:
            context: ..
            dockerfile: AccessCorp.Identity/AccessCorp.WebApi/Dockerfile
        ports:
            - "5225:5225"
        environment:
            - ASPNETCORE_ENVIRONMENT=Docker 
            - ASPNETCORE_URLS=http://*:5225